<?xml version="1.0"?>
<package format="3">
  <name>recovernav_scenarios</name>
  <version>0.2.0</version>
  <description>Controlled Gazebo worlds and dynamic obstacle events for RecoverNav.</description>
  <maintainer email="75089541+panagiotagrosdouli@users.noreply.github.com">panagiotagrosdouli</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
