<?xml version="1.0"?>
<package format="3">
  <name>recovernav_experiments</name>
  <version>0.2.0</version>
  <description>ROS 2 trial runner and metrics logger for RecoverNav.</description>
  <maintainer email="75089541+panagiotagrosdouli@users.noreply.github.com">panagiotagrosdouli</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav2_simple_commander</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
